### ISSUE TITLE
EngineFailure error on fresh install

### ISSUE THREAD

**Issue by alexpjohnson** [codeclimate/codeclimate#18]
Hey, I just created a new codeclimate.yml using `codeclimate init`, validated the config and tried to run `codeclimate analyze`. I got the following error

``error: (CC::Analyzer::Engine::EngineFailure) engine rubocop failed with status 1 and stderr "/usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:121:in `initialize': Permission denied @ rb_sysopen - /code/dd (Errno::EACCES)\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:121:in `open'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:121:in `ruby_executable?'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:78:in `to_inspect?'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:65:in `block in target_files_in_dir'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:64:in `select'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:64:in `target_files_in_dir'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:31:in `find'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/runner.rb:41:in `find_target_files'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:18:in `block in run'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:16:in `chdir'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:16:in `run'\n\tfrom /usr/src/app/bin/codeclimate-rubocop:6:in `<main>'\n"``

The contents of my yml are:
```---
engines:
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- config/**/*
- db/**/*
- test/**/*
- vendor/**/*
```

Any thoughts?

**Comment by mhlavac** [comment]
Running into same problem, I've found out that .codeclimate.yml was belonging to root:root when I created it with init. When I changed it to my user I get

```
error: (CC::Analyzer::Engine::EngineFailure) engine rubocop failed with status 1 and stderr "/usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:121:in `initialize': Permission denied @ rb_sysopen - /code/server/dev/id_rsa (Errno::EACCES)\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:121:in `open'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:121:in `ruby_executable?'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:78:in `to_inspect?'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:65:in `block in target_files_in_dir'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:64:in `select'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:64:in `target_files_in_dir'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:31:in `find'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/runner.rb:41:in `find_target_files'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:18:in `block in run'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:16:in `chdir'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:16:in `run'\n\tfrom /usr/src/app/bin/codeclimate-rubocop:6:in `<main>'\n"
```

Should we force user somehow?

**Comment by mhlavac** [comment]
@alexpjohnson I've found out the issue for me was this: `/code/server/dev/id_rsa (Errno::EACCES)` you have same problem with `/code/dd`, the file belonged to me, but didn't have read permission for everyone. I've changed permissions from 600 to 644 and it's fine.

Of course this is not best solution, in my case it's a dev ssh key that is used to connect to our Docker container and it should really be 600.

**Comment by pbrisbin** [comment]
Thanks for the info, and sorry for the trouble. I think there's a number of subtle user and permissions issues that we'll need to work through to address this.

The generated `codeclimate.yml` being root-owned is not desirable but is expected for the time being. We're stilling working through potential solutions for this, but shouldn't itself cause errors.

The solution for (files like) dev keys is probably to make the engines more tolerant of unreadable files and skip them, rather than erroring. Unfortunately this'll have to be implemented in each engine so it might crop up from time to time.

I've created cards in our internal Trello to track both of these and will report back any progress.

**Comment by pbrisbin** [comment]
@alexpjohnson ( and possibly @mhlavac) I would also recommend putting these files into `exclude_paths` if they're not intended to be analyzed. That should prevent the engine from attempting to read them and solve these errors.

**Comment by pbrisbin** [comment]
@mhlavac can you confirm that adding `- dd/**/*` to `exclude_paths` solves your particular permissions issue?

If so, I'd like to close this and track the general user/permissions problems separately.

> Of course this is not best solution, in my case it's a dev ssh key that is used to connect to our Docker container and it should really be 600.

@alexpjohnson I agree, and would recommend you also try adding `- server/dev/id_rsa` do your exclude_paths and see if that solves the problem, without opening up those permissions.

**Comment by alexpjohnson** [comment]
Hey @pbrisbin,
I updated my yml to:
```---
engines:
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- config/**/*
- db/**/*
- test/**/*
- vendor/**/*
- .rubocop*
- server/dev/is_rsa
- /code/dd
```

and am still receiving this error on `codeclimate analyze`:
```error: (CC::Analyzer::Engine::EngineFailure) engine rubocop failed with status 1 and stderr "/usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:121:in `initialize': Not supported @ rb_sysopen - /code/dd (Errno::EOPNOTSUPP)\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:121:in `open'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:121:in `ruby_executable?'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:78:in `to_inspect?'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:65:in `block in target_files_in_dir'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:64:in `select'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:64:in `target_files_in_dir'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:31:in `find'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/runner.rb:41:in `find_target_files'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:18:in `block in run'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:16:in `chdir'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:16:in `run'\n\tfrom /usr/src/app/bin/codeclimate-rubocop:6:in `<main>'\n"````

**Comment by pbrisbin** [comment]
Hi @alexpjohnson , I'm sorry, my replies were to the opposite users I intended! My first comment was meant for you, and my second for @mhlavac. I've edited the comment to (hopefully) clarify.

The `/code` prefix in the error message can be a bit confusing. Basically your local files are placed in `/code` within the container. The `exclude_paths`, shouldn't include it and should be relative to your local directory.

Please try `- dd/**/*` (not `- /code/dd/**/*`) and see if that fixes it.

**Comment by alexpjohnson** [comment]
@pbrisbin Modifying the .codeclimate.yml as you suggestion did not result in a change on my end.

**Comment by pbrisbin** [comment]
Hmm. OK, I'll have to dig a bit further into this I guess. Is `dd` some kind of special file, a socket or something? `Errno::EOPNOTSUPP` is a strange error.

**Comment by pbrisbin** [comment]
Also, are you able to run `rubocop` on this project normally (not via the Code Climate CLI)?

**Comment by alexpjohnson** [comment]
Yes running rubocop locally results in output.

**Comment by Jared-Prime** [comment]
I am having a similar issue
```
Starting analysis
Running rubocop: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine rubocop failed with status 1 and stderr "/usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:121:in `initialize': Permission denied @ rb_sysopen - /code/tmp/cache/2C5/130/User_cc (Errno::EACCES)\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:121:in `open'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:121:in `ruby_executable?'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:78:in `to_inspect?'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:65:in `block in target_files_in_dir'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:64:in `select'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:64:in `target_files_in_dir'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:31:in `find'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/runner.rb:41:in `find_target_files'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:18:in `block in run'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:16:in `chdir'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:16:in `run'\n\tfrom /usr/src/app/bin/codeclimate-rubocop:6:in `<main>'\n"
```

**Comment by Jared-Prime** [comment]
bump. any news on this issue?

**Comment by GordonDiggs** [comment]
@Jared-Prime I can take a look into this specifically in the morning.In the meantime, do you mean to be analyzing the code in your `tmp` directory? Does it work if you exclude that path?

**Comment by Jared-Prime** [comment]
thank you @GordonDiggs, that helps

however, I have a new failure:
```
$ codeclimate analyze
Starting analysis
Running rubocop: Done!
error: (CC::Analyzer::Engine::EngineFailure) Config for engine rubocop exceeds 64k character limit
```

**Comment by GordonDiggs** [comment]
@Jared-Prime This is a known issue that we are in the process of fixing. I will update this issue when we have a fix!

**Comment by GordonDiggs** [comment]
@Jared-Prime can you update to `0.0.17`, re-run `codeclimate engines:install` and let me know if it is working for you now? We shipped a change to the way we handle the engine configuration that should resolve that

**Comment by acarpe** [comment]
version `0.0.22`, re-ran `codeclimate engines:install` and still continue to get:

```
Starting analysis
Running rubocop: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine rubocop failed with status 1 and stderr
"/usr/src/app/lib/cc/engine/rubocop.rb:16:in `chdir': Permission denied @ dir_chdir - /code (Errno::EACCES)\n\t
from /usr/src/app/lib/cc/engine/rubocop.rb:16:in `run'\n\t
from /usr/src/app/bin/codeclimate-rubocop:12:in `<main>'\n"
```

**Comment by Jared-Prime** [comment]
@GordonDiggs I no longer have this issue with the latest container. Thank you!

As some users apparently still have trouble, do you have any insight into the cause?

**Comment by pbrisbin** [comment]
There have been a number of problems being reported and worked through in this Issue. I'm going to try and summarize:

Resolved:

- @mhlavac permission denied on `id_rsa`

  Excluding or modifying permissions solved the problem

- @Jared-Prime can't access `tmp` stuff

  Excluding (once to "excludes too big" problem was fixed) solved the problem

Open:

- @alexpjohnson permission denied on `dd`

  We're definitely working on making excludes more intuitive, but I think the issue here is still that our attempts to exclude this directory aren't working. I would try the following:

  ```
  exclude_paths
  - dd
  - dd/**
  ```

- @acarpe can't work in the `/code` directory itself

  This is new, and I believe a different kind of error than @alexpjohnson 's or the other follow-on issues. Would you please open a new GitHub issue where we can trouble shoot it specifically?

**Comment by Jared-Prime** [comment]
Wonderful, thank you once again for educating us!

**Comment by acarpe** [comment]
@pbrisbin done! see #54

**Comment by pnomolos** [comment]
I am also running into this issue - fresh install today:

```
Permission denied @ rb_sysopen - /code/tmp/cache/A97/930/settings%3Adata_guard_links (Errno::EACCES)
```


__Full Error__
```
error: (CC::Analyzer::Engine::EngineFailure) engine rubocop failed with status 1 and stderr "/usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:121:in `initialize': Permission denied @ rb_sysopen - /code/tmp/cache/A97/930/settings%3Adata_guard_links (Errno::EACCES)\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:121:in `open'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:121:in `ruby_executable?'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:78:in `to_inspect?'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:65:in `block in target_files_in_dir'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:64:in `select'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:64:in `target_files_in_dir'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:31:in `find'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/runner.rb:41:in `find_target_files'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:18:in `block in run'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:16:in `chdir'\n\tfrom /usr/src/app/lib/cc/engine/rubocop.rb:16:in `run'\n\tfrom /usr/src/app/bin/codeclimate-rubocop:12:in `<main>'\n"
```

My `.codeclimate.yml` is as follows:

```yaml
# Save as .codeclimate.yml (note leading .) in project root directory
engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  bundler-audit:
    enabled: true
ratings: #Specifies which files/paths will be graded.
  paths:
  - "app/**"
  - "lib/**"
  - Gemfile.lock
exclude_paths:
  - "spec/**/*"
  - "db/*"
  - "app/assets/javascripts/vendor/*"
  - "app/assets/javascripts/static/*"
  - "tmp/**"
  - "tmp/**/*"
  - "tmp/cache/**"
  - "tmp/cache/**/*"
```

**Comment by pbrisbin** [comment]
Hmm, that's strange. I would have expected the `- "tmp/**"` entry to work and prevent rubocop from trying to read that file. I'm sorry to not have an answer yet, but I'll keeping digging into this and report back any findings.

**Comment by pnomolos** [comment]
@pbrisbin Thanks!

**Comment by pnomolos** [comment]
@pbrisbin I have an idea on this one - in our project `./tmp/cache` is used as a cache directory - I'm _guessing_ that if files are generated in that directory __after__ the initial calculation of directories then they'll still be parsed?

**Comment by pbrisbin** [comment]
Hmm, that does seem possible. But I can't picture a way files would be generated after the list of files to exclude is built but before the analysis is run. Are you running tests, or the app in another terminal at the same time as the `codeclimate analyze` command?

**Comment by pnomolos** [comment]
@pbrisbin I did realize after I wrote the comment that this explanation seems implausible :)

**Comment by sergey-alekseev** [comment]
I installed CodeClimate locally and I get:
```
❯ codeclimate analyze                ✭ ✱
Starting analysis
Running rubocop: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine rubocop failed with status 1 and stderr 
/usr/lib/ruby/gems/2.2.0/gems/rubocop-0.31.0/lib/rubocop/target_finder.rb:121:in `initialize': Permission denied @ rb_sysopen - /code/tmp/archive/extract/RackMultipart20150911-11827-872ref.zip/dbcf4df20d4a29738cf8c4d705f516e0 (Errno::EACCES)
```

Seems there is still no fix for that.

**Comment by pbrisbin** [comment]
@sergey-alekseev (and @pnomolos), we identified (and spent a lot of time fixing) #82 which may be what's happening here. So far we've only made the fix in the eslint engine but are in the process of updating other engines. I'll report back once we've made the same fix to rubocop and see if that addresses things.

**Comment by fhwang** [comment]
We've now pushed changes to `codeclimate-rubocop`. Can you try updating your image and then giving it a try?

**Comment by sergey-alekseev** [comment]
I've run `codeclimate engines:enable rubocop` and now `codeclimate analyze` works! Good job, guys :clap: 

However it basically works similar to `rubocop`. I hoped to see the same result as on CodeClimate - issues for changes only, not for the entire codebase.

**Comment by alexpjohnson** [comment]
Works for me as well. Thanks guys

**Comment by GordonDiggs** [comment]
Awesome! Glad it's working. Going to close this issue out and we will be working on bringing this fix to other engines in the next few weeks.

**Comment by pnomolos** [comment]
Looks good, thanks!
