### ISSUE TITLE
How to generate codeclimate configuration?

### ISSUE THREAD

**Issue by rhwood** [codeclimate/codeclimate#810]
The [Configuring Your Analysis](https://docs.codeclimate.com/docs/getting-started-configuration) documentation states:

> For repos added after July 2017, the .codeclimate.yml may not be available at the above-mentioned URL. If you experience a 404, please generate the .codeclimate.yml locally by using the Code Climate CLI.

However, I see no way to do that using the codeclimate CLI. Is the documentation incorrect, a CLI command undocumented, or something else I should be doing?

**Comment by rhwood** [comment]
I found the link on https://docs.codeclimate.com , step 2 "Configuration"

**Comment by wfleming** [comment]
Dave deleted the out-of-date page, and the link on docs.codeclimate.com has been updated to point to an up-to-date document: https://docs.codeclimate.com/docs/configuring-your-analysis.

I'm going to close this as I believe we've addressed the issue. @rhwood I'm sorry we dropped the ball with the docs, and that led to confusion. Thank you for pointing out the issue! If you're still having trouble let us know.

**Comment by dgw** [comment]
This documentation issue still exists, I believe. Either that, or I found another path to it.

Followed a link to this repo from https://docs.codeclimate.com/docs/configuring-your-code-climate-analysis (which says to generate a config with this CLI tool) from https://docs.codeclimate.com/docs/default-analysis-configuration just this afternoon, and then installed Docker on my system to pull the CLI only to find that it can't generate a configuration for me. :disappointed:

**Comment by efueger** [comment]
Sorry about that @dgw! I think you found a different path.
- What repo are you working with? I can create a config file for you.
- If you happen to remember how you got to the link, let me know and I'll make a note to fix it. 👍 

Thanks for your help.

**Comment by efueger** [comment]
Ha! No worries @dgw. 
- I've opened a pull request with that [here](https://github.com/sopel-irc/sopel/pull/1329).
